/**
 * Componentes UI - Exports centralizados
 *
 * Uso:
 * import { AppLayout, PageWrapper, Input, Button, Card, ... } from '../components/ui'
 */

export { AppLayout } from './AppLayout'
export { PageWrapper } from './PageWrapper'
export { Input } from './Input'
export { Button } from './Button'
export { Card } from './Card'
export { Countdown } from './Countdown'
export { ProgressBar } from './ProgressBar'
export { BottomNav } from './BottomNav'
export { JourneyStep } from './JourneyStep'
export type { JourneyStepProps, JourneyStepStatus } from './JourneyStep'
export { PageHeader } from './PageHeader'
export { LiveTicker } from './LiveTicker'
export { RadarChart } from './RadarChart'
export type { IMPACTData } from './RadarChart'
export { DiagnosticSlider } from './DiagnosticSlider'
export { GargaloAlert } from './GargaloAlert'
export { LockedOffer } from './LockedOffer'
export { SystemAlert } from './SystemAlert'
export type { AlertType } from './SystemAlert'
export { FinalReport } from './FinalReport'
export { ScenarioProjection } from './ScenarioProjection'
export { ActionPlan } from './ActionPlan'
export type { ActionItem } from './ActionPlan'

// Novos componentes v2
export { NotificationToast } from './NotificationToast'
export type { ToastNotification, ToastNotificationType } from './NotificationToast'
export { NotificationDrawer } from './NotificationDrawer'
export { NPSModal } from './NPSModal'
export type { NPSType } from './NPSModal'
export { PresenceConfirmCard } from './PresenceConfirmCard'
export { AvatarButton } from './AvatarButton'
export { ProfileCard } from './ProfileCard'
export { AIChatFAB } from './AIChatFAB'
export { AIChatInterface } from './AIChatInterface'
export { SponsorBadge } from './SponsorBadge'
export { NPSForm } from './NPSForm'
export { ProtectedRoute } from './ProtectedRoute'
export { ProfileModal } from './ProfileModal'
export { EventCountdown } from './EventCountdown'
export { EventFinishedView } from './EventFinishedView'
export { ConfirmationModal } from './ConfirmationModal'
export { LiveEventModal } from './LiveEventModal'
